name: TravHouseAPI
version: 1.0
main: com.travhouse.api.TravHouseAPIPlugin
api-version: 1.19
author: TravHouse
description: API плагин для админ-панели TravHouse

commands:
  thapi:
    description: Команды плагина TravHouse API
    usage: /thapi <reload|status|port>
    permission: travhouse.admin

permissions:
  travhouse.admin:
    description: Доступ к командам TravHouse API
    default: op
  travhouse.api.access:
    description: Доступ к API
    default: true